DROP TABLE IF EXISTS CLIENT;

CREATE TABLE "CLIENT"(
    "ID" VARCHAR2(6) NOT NULL PRIMARY KEY,
    "NAME_CLIENT" VARCHAR2(48) NOT NULL,
    "SURNAME_CLIENT" VARCHAR2(48) NOT NULL,
    "EMAIL" VARCHAR2(60) NOT NULL,
    "AGE" NUMBER
);
